### ISSUE TITLE
puppet-omnibus didn't work with puppet-rundeck.

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#45]
Not sure with this issue, which github repository I need target (`puppet-rundeck` or `andytinycat/puppet-omnibus`), but since we use `puppet-omnibus` with other forge packages and private packages without this issue, so I put my issue here.

My office use `puppet-omnibus` on all puppet agents. 

I install puppet-rundeck with puppetlabs puppet/facter/hierada without issue. But when install with `puppet-omnibus`, the first time when run `puppet apply` directly, rundeck is successfully installed, I can see the services running on port 4440. Then I got this error with any puppet command:

```
$ puppet --version
Starting puppet agent: /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:73:in `parse': undefined method `each_line' for nil:NilClass (NoMethodError)
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:120:in `results'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:61:in `block in load'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:55:in `each'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:55:in `load'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/composite_loader.rb:10:in `block in load'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/composite_loader.rb:10:in `each'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/composite_loader.rb:10:in `load'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/collection.rb:109:in `load'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/collection.rb:84:in `fact'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/collection.rb:139:in `value'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter.rb:112:in `block (2 levels) in singleton class'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet/defaults.rb:4:in `default_diffargs'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet/defaults.rb:183:in `<module:Puppet>'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet/defaults.rb:1:in `<top (required)>'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet.rb:109:in `<module:Puppet>'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet.rb:29:in `<top (required)>'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/lib/puppet/util/command_line.rb:12:in `<top (required)>'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
   from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/puppet-3.3.1/bin/puppet:3:in `<top (required)>'
   from /usr/bin/puppet:23:in `load'
   from /usr/bin/puppet:23:in `<main>'
```

let me know what I need check, seems the root cause is related to facter command. 

puppet-omnibus version is 3.3.1
Linux version is CentOS 6.5

**Comment by SydOps** [comment]
I uninstalled puppet-omnibus package, and install again, get same error when run puppet command.

I uninstalled puppet-omnibus package and install with `yum install puppet-3.3.1 facter hiera`, no issue found.

**Comment by liamjbennett** [comment]
Once you have it installed can you check the output of the /etc/facter/facts.d/rundeck_version script? Given the error you are seeing is with facter perhaps this fact is returning something erroneous.

**Comment by SydOps** [comment]
puppet environment is broken with puppet-omnibus, but with puppetlabs puppet, i still can see this error:
```
/usr/lib/ruby/site_ruby/1.8/facter/util/directory_loader.rb:80: command not found: /etc/facter/facts.d/rundeck_version
Fact file /etc/facter/facts.d/rundeck_version was parsed but returned an empty data set
```

If I directly run it with bash, no output
```
[root@rundeck log]# bash /etc/facter/facts.d/rundeck_version
[root@rundeck log]#
```

Read the content in it, our system is CentOS 6.5, and dpkg is not installed by default.

    Linux version is CentOS 6.5

**Comment by SydOps** [comment]
Yes, your prompt gives me the way to fix it. After install dpkg package, the problem is fixed. 

Maybe i can help to fix this issue to add centos support. In CentOS, I run below yum command to get rundeck version.
```
yum list installed |grep rundeck
Repository 'Pulp' is missing name in configuration, using id
rundeck.noarch              2.5.0-1.6.GA       @bintray-rundeck
rundeck-config.noarch       2.5.0-1.6.GA       @bintray-rundeck
```

**Comment by SydOps** [comment]
Find the code in `manifests/config.pp`

```
  ensure_resource('file', ['/etc/facter', '/etc/facter/facts.d'], {'ensure' => 'directory'})

  file { '/etc/facter/facts.d/rundeck_version':
    ensure => present,
    source => 'puppet:///modules/rundeck/rundeck_version',
    owner  => root,
    group  => root,
    mode   => '0755'
  }
```

**Comment by SydOps** [comment]
i see, the problem is fixed by #42

**Comment by SydOps** [comment]
this change (b4bc451) makes trouble. 

I faced some issues (#45) which I think it is fixed by #42 and apply the latest commit.

After apply the new change, i saw more errors:
```
# puppet agent -t
/opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/resolution.rb:171:in ``': Interrupt
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/resolution.rb:171:in `block in exec'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/resolution.rb:130:in `with_env'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/resolution.rb:156:in `exec'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:120:in `results'
...
/opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:73:in `parse': undefined method `each_line' for nil:NilClass (NoMethodError)
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:120:in `results'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:61:in `block in load'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:55:in `each'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:55:in `load'

```

**Comment by SydOps** [comment]
If I run below command, 
```
[root@rundeck log]# facter |grep rundeck
Write failed: Broken pipe
```

**Comment by liamjbennett** [comment]
Ok, that's a little unusual. Thank's for the PR. 

I want to take a look into this a bit more and write some tests first so I can understand the problem a bit better.

**Comment by SydOps** [comment]
You need stick on commit f8f1dddf6b7d6530d3a6f8ecd5736a5547a885b6 (release v1.1.0)

For anyone who has the same issue, here is my work around. Put below code before you call `include  rundeck`. 

```
  file { '/var/lib/dpkg':
    ensure => directory,
  }
  file { '/var/lib/dpkg/updates':
    ensure => directory,
  }
  file { '/var/lib/dpkg/status':
    ensure => file,
  }
  file { '/var/lib/dpkg/available':
    ensure => file,
  }
  package { 'dpkg':
    ensure  => installed,
    require => File['/var/lib/dpkg','/var/lib/dpkg/updates','/var/lib/dpkg/status','/var/lib/dpkg/available']
  }
```

**Comment by liamjbennett** [comment]
Thanks @SydOps this is very useful.

**Comment by SydOps** [comment]
@liamjbennett 

Will any above commits to be merged soon?  `5520b31` or `88c85e8`

**Comment by SydOps** [comment]
ic, https://github.com/wcooley/puppet-rundeck/commit/5520b310fb181c02caaa368b60eff88a02198d47 has been merged. 
This issue can be closed now.

**Comment by SydOps** [comment]
I can confirm this issue has been fixed properly, I needn't install dpkg as work around any more.

**Comment by SydOps** [comment]
I start from a new system (rundeck is not installed) and then i saw the issue again. Seems the problem is not fixed in puppet-omnibus
```
root@rundeck facts.d]# puppet agent -t --noop
/opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:73:in `parse': undefined method `each_line' for nil:NilClass (NoMethodError)
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/parser.rb:120:in `results'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:61:in `block in load'
	from /opt/puppet-omnibus/embedded/lib/ruby/gems/2.0.0/gems/facter-1.7.3/lib/facter/util/directory_loader.rb:55:in `each'
```

**Comment by SydOps** [comment]
We are planning to get rid of `puppet-omnibus` from our system, since this issue is only reported with `puppet-omnibus`, and I have work around to resolve it, this issue should be fine to be closed now.
